import re

from .web import WebLogfileReader


class NginxLogfileReader(WebLogfileReader):
    """Parses logfiles generated by nginx.
    """

    REGEX = [
        re.compile(
            r"""
            ^(?P<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})
            \ \[(?P<timestamp>[^\]]+)\]
            \ "(?P<request>.*?)"
            \ (?P<status>\d+)
            \ (?P<size>\d+)
            \ (?P<duration>[\d\.]+)
            \ "(?P<referer>.*?)"
            \ "(?P<useragent>.*?)"
            \ (?P<host>.+)$
            """,
            re.VERBOSE
        )
    ]
