import re
import functools

from datetime import datetime

from .base import RegexLogfileReader

from .utils import asUTC, get_file_date


def parse_postfix_timestamp(year, datestring):
    """Converts the date and time in postfix logs to a `datetime` instance."""
    return asUTC(datetime.strptime('{} {}'.format(year, datestring), "%Y %b %d %H:%M:%S"))


class PostfixLogfileReader(RegexLogfileReader):
    """Parses logfiles generated by the Postfix server.

    Returns a dictionary with the following keys:
    - timestamp
    - server
    - process
    - process_id
    - message_id
    - message
    """

    FIELD_NAMES = ['timestamp', 'server', 'process', 'process_id', 'message_id', 'message']

    REGEX = [
        re.compile(
            r"""
            ^(?P<timestamp>[A-Za-z]{3}[ ]+[\d]{1,2}\ \d\d:\d\d:\d\d)
            \ (?P<server>[a-z0-9]+)
            \ postfix/(?P<process>[a-z]+)\[(?P<process_id>[\d]+)\]:
            \ (?P<message_id>[A-Z0-9]{11}):
            \ (?P<message>.+)$
            """,
            re.VERBOSE
        ),
        re.compile(
            r"""
            ^(?P<timestamp>[A-Za-z]{3}[ ]+[\d]{1,2}\ \d\d:\d\d:\d\d)
            \ (?P<server>[a-z0-9]+)
            \ postfix/(?P<process>[a-z]+)\[(?P<process_id>[\d]+)\]:
            \ (?P<message>.+)$
            """,
            re.VERBOSE
        )
    ]

    @classmethod
    def process_result(cls, d):
        """Parse message into a dictionary of name value pairs"""
        pass

    def __init__(self, filenameOrFile):
        super(PostfixLogfileReader, self).__init__(
            filenameOrFile, type_mapper={
                # we need a year part to get a date time, but postfix doesn't output the year.
                # so instead we guess the year part from the time the file was created
                'timestamp': functools.partial(parse_postfix_timestamp, get_file_date(filenameOrFile).year),
                'process_id': int
            })
